spring:
  http:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 10MB
  datasource:
      hikari:
        minimum-idle: 1
        maximum-pool-size: 20
        connection-timeout: 30000
      type: com.zaxxer.hikari.HikariDataSource
  jpa:
      properties:
        hibernate:
          default_schema: public
          ddl-auto: validate
      show-sql: false
  data:
    elasticsearch:
      properties:
        node.local: true
        path.data: data/
        path.home: home/
        path.conf: config/
        index.search.slowlog.threshold.query.info: "1ms"
        index.search.slowlog.threshold.fetch.info: "1ms"
      cluster-name: item-api

server:
  port: 80

flyway:
  schemas: public
